name: Deploy React App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Generate ZIP file for deployment
      run: zip -r deploy.zip build

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: YourElasticBeanstalkAppName
        environment_name: YourElasticBeanstalkEnvName
        region: your-region-1
        version_label: v-${{ github.run_number }}
        deployment_package: deploy.zip
