name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip files for deployment
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: AKIA46ZQ3CFNZFXI2PUV
          aws_secret_key: 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
          application_name: MyCiCd Project
          environment_name: MyCiCdProject-env
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
